name: Deploy Aurora Free to VPS

on:
  push:
    branches:
      - live   # change if your branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build project
        run: npm run build

      # 5. Deploy to VPS via SSH
      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/*"
          target: "/var/www/html/aurora-free/aurora"
          strip_components: 1